Ranagol/simplelogistik

app/Http/Controllers/TmsOrderController.php, app/Http/Resources/TmsOrderEditResource.php, app/Models/TmsOrder.php, app/Models/TmsOrderAddress.php, app/Services/OrderService.php, database/factories/TmsOrderFactory.php, database/migrations/2024_01_24_120328_add_shipping_label_pdf_to_orders.php, database/seeders/TmsOrderAddressSeeder.php
In orders table:
- change payment_method to integer.
- add shipping_label_pdf string nullable column.
=> Order changes

app/Http/Controllers/TmsOrderController.php, app/Http/Resources/TmsOrderEditResource.php, app/Models/TmsOrder.php, app/Models/TmsOrderAddress.php, app/Services/OrderService.php, database/factories/TmsOrderFactory.php, database/factories/TmsParcelFactory.php, database/migrations/2023_12_11_101309_create_tms_parcels_table.php, database/migrations/2024_01_24_120328_add_shipping_label_pdf_to_orders.php, database/migrations/2024_01_24_122855_rename_column_in_parcels.php, database/seeders/TmsOrderAddressSeeder.php
Remove _p from parcel column names and adapt parcel factory.
=> Parcel changes

database/factories/TmsForwarderFactory.php, resources/js/Components/Sidebar/Sidebar.vue, resources/js/Components/Tables/ConditionalBodyColumn.vue, resources/js/Components/Tables/OrderTableRowWithContent.vue, resources/js/Components/Tables/OrderTableWithContent.vue, resources/js/Pages/Orders/IndexOrder/Index.vue, resources/js/config/mainMenu.js, resources/lang/de.json, vite.config.js
- added an array, containing the forwarder image urls which are then picked randomly while seeding
- extracted menu configuration
- build dynamic sidebar by looping through menu config
- add JS config folder as Alias  to vite config
- update image design
- fix unknown key in headers object which prevented the view to be rendered
- rearrage table structure
- renamed headers to be more obvious, that this is default
- added some translation keys
=> dev pds styling

app/Console/Commands/PamyraOrders.php, app/Console/Kernel.php
shall show that the LINUS cronjob is pushing the laravel's scheduler
=> cronjobTESTforpamyra

Modules/PamyraOrder/app/Services/PamyraServices/OrderHandler.php, Modules/PamyraOrder/app/Services/PamyraServices/OrderService.php, app/Models/TmsAddress.php, app/Models/TmsOrder.php, app/Models/TmsOrderAddress.php, database/migrations/2024_01_09_155453_create_tms_order_addresses_table.php, database/migrations/2024_02_19_154711_remove_billing_address_id_from_orders.php, database/seeders/TmsOrderAddressSeeder.php, database/seeders/TmsOrderSeeder.php
When creating a pamura order from pamyra json file, a billing address must be created in the tms_order_addresses table.
=> Billing address logic change

Modules/PamyraOrder/app/Console/HandlePamyraOrders.php, Modules/PamyraOrder/app/Services/PamyraServices/AddressService.php, Modules/PamyraOrder/app/Services/PamyraServices/OrderHandler.php
Fix missing pickup and delivery address creation, so these addresses are created not just in tms_order_addresses but also in tms_addresses.
Improve street-number separation process.
=> Fix missing pickup and delivery address. 

app/Http/Controllers/TmsOrderController.php, app/Traits/DataBaseFilter.php
Sort order by order_date column.
=> Sort order by order_date column.

Modules/PamyraOrder/app/Services/PamyraServices/OrdersHandler.php, Modules/PamyraOrder/app/Services/PamyraServices/PamyraOrderService.php
In tms_pamyra_orders and in tms_native_orders must create a particularities column. This is basically customers reference. This is in 'particularities' in Pamyra json file.
=> Make particularities column work.

Modules/PamyraOrder/app/Services/PamyraServices/OrderHandler.php
Do not create TmsAddress records during Pamyra json file processing.
=> Do not create TmsAddress records during Pamyra json processing.

Modules/PamyraOrder/app/Services/PamyraServices/OrderService.php, database/migrations/2024_02_23_144741_add_owner_to_orders.php
Set pruchase price to 0, add owner to orders.
=> Set pruchase price to 0, add owner to orders.

app/Http/Controllers/TmsAddressController.php, app/Http/Requests/TmsAddressRequest.php
Patrick said that I can merge this.
=> Small fixes.

resources/js/Pages/Customers/Create.vue
- Update `:page` prop to `:content` prop in `Page` component.
- Add `:store` prop to `Page` component.
This change was made to ensure that the correct data is passed to the `Page` component and to include the `store` prop for proper functionality.
=> 🔧 fix: update Page component props in template

resources/js/Pages/Forwarders/Create.vue, resources/js/Pages/Forwarders/Edit.vue, resources/js/Pages/Vehicles/Edit.vue, resources/js/config/Pages/Forwarders/Form/_config.js
This commit adds new sections and fields to the customer information form. The sections include fields such as ID, company name, internal ID, name, email, tax number, rating, forwarder type, and comments. These fields are necessary for capturing relevant information about the customer.
=> ✨ feat: add sections and fields to customer information form

resources/js/Components/Editors/AddressesEditor.vue, resources/js/Components/Editors/ParcelEditor.vue, resources/js/Components/Form.vue, resources/js/Components/Inputs/BindableTextField.vue, resources/js/Components/Page.vue, resources/js/config/Pages/Orders/Form/_details.js, resources/js/lib/OrderCalcHelper.js, resources/lang/de.json
The changes in this commit refactor the parcel component to use reactive state and calculate parcel calculations using the OrderCalcHelper. This improves the code structure and makes it easier to manage and update the parcel data.
=> 🎨 style: refactor parcel component to use reactive state and calculate parcel calculations

app/Http/Controllers/TmsVehicleController.php
=> Error fixed.

resources/js/Components/Boxes/OrderAddressBox.vue, resources/js/Components/Boxes/OrderDetailBox.vue, resources/js/Components/Boxes/OrderParcelBox.vue, resources/lang/de.json
- Updated font color in group and single item labels
- Updated background color in a specific section of the template
- Updated translations for badge labels
- Added translations for address labels and general labels
- Updated styling for badge labels in a specific section of the template
=> 🎨 style: update styling and translations in client UI

resources/js/Components/Editors/AddressesEditor.vue, resources/js/Components/Form.vue, resources/js/config/Pages/Orders/Form/_details.js
- Removed duplicate form fields in the order details page.
- Updated the form field for partner selection to use a dropdown with options from the "partners" data source.
- Updated the form field for order status selection to use a dropdown with options from the "orderstatuses" data source.
- Removed unnecessary code and formatting in the template file.
=> ✨ feat: update form fields and sections in the order details page

app/Models/TmsParcelType.php, database/factories/TmsParcelFactory.php, database/seeders/DatabaseSeeder.php, database/seeders/TmsParcelTypeSeeder.php
Add booleans and nested array to parcel types.
=> Add booleans and nested array to parcel types.

resources/js/Layouts/AuthenticatedLayout.vue
The layout classes in the main component have been adjusted to ensure proper positioning and spacing.
=> 🔧 fix: adjust layout classes in main component

resources/js/Components/Inputs/BindableTextField.vue, resources/js/Pages/Orders/Edit.vue, resources/js/Pages/Orders/Parts/OrderEditDetails.vue, resources/js/config/Pages/Orders/Form/_details.js, resources/lang/de.json
-add function copyAddressToClipboard
=> 🔨 fix: layout issues, translations, changable address_type

database/factories/TmsOrderFactory.php, database/migrations/2023_11_12_000008_create_tms_orders_table.php, database/migrations/2024_03_05_082043_change_month_and_year_in_orders.php, database/seeders/TmsOrderSeeder.php
Change month_and_year in tms_orders from string to date format.
=> Change month_and_year in tms_orders from string to date format.

Modules/PamyraOrder/app/Services/PamyraServices/ParcelService.php, app/Models/TmsParcelType.php, database/factories/TmsParcelTypeFactory.php, database/seeders/TmsParcelTypeSeeder.php, test.txt
Assign parcel_type_id in tms_parcels for every pamyra order.
=> Palett type adding

app/Models/TmsProvision.php, app/Models/TmsTransportRule.php, database/seeders/TmsProvisionSeeder.php, database/seeders/TmsTransportRuleSeeder.php
Provision seeding and transport rule seeding fixed. Instead of inserting, we use now models to create db records.
=> Insert corrections

database/seeders/DatabaseSeeder.php
=> ParcelTypeSeeder enabled.

Modules/PamyraOrder/app/Services/PamyraServices/OrderService.php, database/factories/TmsForwarderFactory.php, database/migrations/2024_03_06_104547_add_slug_to_forwarders.php, database/seeders/TmsForwarderSeeder.php
Add slug column to forwarders table, adapt app logic and seeder accordingly.
=> Slug forwarders

app/Http/Controllers/TmsOrderController.php, app/Http/Resources/TmsOrderIndexResource.php, app/Models/TmsOrder.php, database/seeders/TmsOrderAddressSeeder.php
Add new orderAddress order in the for the orders index page.
=> Add new orderAddress order in the for the orders index page.

Modules/PamyraOrder/app/Services/PamyraServices/PamyraOrderService.php, app/Http/Requests/TmsNativeOrderRequest.php, app/Http/Requests/TmsPamyraOrderRequest.php, database/factories/TmsNativeOrderFactory.php, database/factories/TmsPamyraOrderFactory.php, database/migrations/2024_03_07_094443_change_pamyra_orders_km_min.php, database/migrations/2024_03_07_094507_change_native_orders_km_min.php, database/seeders/DatabaseSeeder.php, test.txt
Change km and min from float to integer in tms_pamyra_orders and tms_native_orders.
=> Km and min

app/Http/Controllers/TmsOrderController.php
Add resource data formatting to show and edit pages for orders.
=> Add resource data formatting to show and edit pages for orders.

app/Models/TmsOrderStatus.php
=> Change order statuses.

app/Models/TmsTransportRule.php
=> Change transport rule.

app/Http/Controllers/TmsOrderController.php, app/Http/Resources/TmsOrderIndexResource.php, app/Models/TmsOrderAddress.php
Add country code like 'DE' to orderAddresses.
=> Country code

Modules/PamyraOrder/app/Services/PamyraServices/OrderService.php, app/Http/Controllers/TmsOrderController.php, app/Http/Resources/OrderResources/IndexCollection.php, app/Http/Resources/OrderResources/IndexResource.php, app/Http/Resources/OrderResources/ShowEditResource.php, app/Http/Resources/TmsOrderIndexResource.php, app/Models/TmsOrderStatus.php, app/Services/OrderService.php, database/factories/TmsOrderFactory.php, database/seeders/TmsOrderStatusSeeder.php
Change order resource pickup and delivery date.
Restructure and reposition and rename order resources.
Add order status text to the response.
=> Change order resource
